### ISSUE TITLE
Translating terms is not saving the language correctly

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#72] opened 2021-04-23 15:17 UTC
`When translating a term on a vocabulary with "translate" set (as opposed to "localize"), the language selection is set correctly and locked on the translation page, but the resulting term is saved as language undefined -- so it is not attached to the translation set. 

As a workaround, I can then go in and edit the term, change the language to the appropriate language and save the term, then go back to the original term and link it in the translations tab.

This is on `v1.x-1.0.0-alpha2`. I don't see any errors or warnings in the log.

**Comment by laryn** [comment] 2021-04-23 16:08
PR submitted: https://github.com/backdrop-contrib/i18n/pull/73

Not sure if this core fix is needed as well: https://github.com/backdrop/backdrop/pull/3606

**Comment by indigoxela** [comment] 2021-04-24 09:07
I don't think your PR is correct.

`if (!$form_state['values']['language'])` this means that the **vocabulary** has no multilingual support (that's core).

Function i18n_taxonomy_form_vocabulary_submit() handles vocabs, but your report is about terms. So this is definitely the wrong function.

**Comment by indigoxela** [comment] 2021-04-24 09:09
The core bug you linked, is totally unrelated. It's about the weight of a pseudo field, which has impact on field display.

**Comment by indigoxela** [comment] 2021-04-24 09:28
I can't reproduce the problem. Term translation just works fine. Did you change the translation mode of that vocab at some point in the past? Means: did you switch from localize to translate?

**Comment by laryn** [comment] 2021-04-24 11:45
> Means: did you switch from localize to translate?

Most likely yes. It's the same dev site as the other recent hard-to-reproduce issue. :smile_cat: 

I'll try to reproduce on a fresh server and rework the PR if needed. I was casting at straws a bit and it was a bit surprising that this actually caused it to start working...

**Comment by indigoxela** [comment] 2021-04-24 12:19
Yes, switching the type when there's already data, can have some side effects. Hard to catch sometimes.

> I was casting at straws a bit and it was a bit surprising that this actually caused it to start working...

More than surprising, actually :smile:

**Comment by indigoxela** [comment] 2021-09-10 06:27
Closing this issue, as the problem wasn't reproducible for me and nobody else confirmed.

@laryn feel free to reopen, if there are new infos about your problem.

**Closed as completed by indigoxela** 2021-09-10 06:27 UTC
Labels: can't reproduce
