### ISSUE TITLE
Table i18n_translation_set already exists

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/i18n#43] opened 2021-01-12 21:21 UTC
Will need to check before trying to create the table. Not sure best way to do this since I think it's just defining it in the schema, not in an update hook.

**Comment by indigoxela** [comment] 2021-01-13 07:41
Did you try to upgrade from a D7 (we have no upgrade path yet), or was that a fresh install? Could you provide your steps, please?

**Comment by herbdool** [comment] 2021-01-14 16:23
I did an upgrade from D7. I was getting dependency issues like "variable_realm, variable_store: is missing" (probably because `system` table still had the old dependencies listed. So I disabled this and other submodules which previously relied on it. 

But apparently I was to run the upgrade eventually by doing it via drush which for some reason doesn't care if there are unmet dependencies. So maybe the better approach here is to figure out how to deal with the dependency issues - might not be anything we can do in 1i8n.

**Comment by indigoxela** [comment] 2021-01-14 16:31
> might not be anything we can do in i18n.

It might be possible, but could get harder. Someone in the chat with a similar problem (different module(s)) had success with dummy modules.

Add empty module placeholders (just a .module and a .info file with minimal data) to your Backdrop module directory - just to see if that works for you...
The (unported/unportable) variable module makes things difficult.

**Comment by indigoxela** [comment] 2021-01-16 11:50
Another thought came to my mind: currently module i18n_variable is still there, but hidden. Update hooks also run for disabled modules.

@herbdool Do you have the same problems if you completely delete the i18n_variable directory? I've no idea how the upgrade handles changed dependencies in existing modules.

Update: deleting the directory is a bad idea as long as the entry in system table is still there, but removing all code might work.

**Comment by indigoxela** [comment] 2021-04-03 08:20
@herbdool the first alpha is out. There hasn't been any update here regarding possible root causes or steps to reproduce, so I'm closing this one as outdated. Feel free to re-open if there are any new findings regarding the database table.

**Closed as completed by indigoxela** 2021-04-03 08:20 UTC
