### ISSUE TITLE
View that lists localized terms

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#64] opened 2021-03-24 17:07 UTC
I've run into a case where a view that displays localized taxonomy terms is showing them in the source language always. There is no option (for example) for adding the term name in localized format.

We can probably pluck out a handler or two from `i18nviews` and add it to the `i18n_taxonomy` module.

**Comment by laryn** [comment] 2021-03-24 17:19
Possibilities:

 - Term name: https://github.com/laryn/i18nviews/blob/1.x-3.x/includes/i18nviews_handler_field_taxonomy_term_name.inc
 - Term description: https://github.com/laryn/i18nviews/blob/1.x-3.x/includes/i18nviews_handler_field_taxonomy_term_description.inc

**Comment by indigoxela** [comment] 2021-03-26 14:29
Hey, @laryn you already gave porting a try.

How far did you get? Does i18nviews help with the exposed forms?

**Comment by laryn** [comment] 2021-03-26 15:02
@indigoxela Yes, I have enabled the port on this dev site and both issues are resolved. I have linked my best guess as to which handlers are needed for each issue.

**Comment by indigoxela** [comment] 2021-03-26 15:33
Hm, only the two linked files won't do the trick, it needs a lot more. Probably most files from the includes directory and then all autoload info and views_data_alter stuff.

This makes me think that this module might better stay its own project, i18n is already a hard to tame monster.

**Comment by indigoxela** [comment] 2021-03-26 15:48
A quick hint re https://github.com/laryn/i18nviews/blob/343ea42c71bbeb2ea3db643ec9561a1b33c875ad/i18nviews.module#L30

That's `$plugin = config_get('views.settings', 'views_localization_plugin');`

**Comment by indigoxela** [comment] 2021-03-26 16:02
Hm... there seems to be a bug in i18nviews filters. The filter _shows_ localized terms, but doesn't filter correctly for them - nodes using a language neutral localized term do not appear in the result list. Could be my sloppy quick setup, though.

It feels a bit odd, to discuss this in the i18n queue, when I resist to include that module in the i18n project. :smile:

**Comment by laryn** [comment] 2021-03-26 16:03
> This makes me think that this module might better stay its own project, i18n is already a hard to tame monster.

Since views is in core, my thought was it should not require a separate download. If it can't easily be integrated directly into `i18n` how about bundling it as a submodule in `i18n`?

**Comment by laryn** [comment] 2021-03-26 16:04
> Hm... there seems to be a bug in i18nviews filters. The filter shows localized terms, but doesn't filter correctly for them - nodes using a language neutral localized term do not appear in the result list. Could be my sloppy quick setup, though.

Easily there could be bugs. This is a very quick port and I just tested for my immediate need so far...

**Comment by indigoxela** [comment] 2021-03-26 16:05
> If it can't easily be integrated directly into i18n how about bundling it as a submodule in i18n?

Not as long as I'm the only active maintainer. I spent way too many hours with i18n, and that's still ongoing. Why should I increase my pain. :grin:

**Comment by laryn** [comment] 2021-03-26 16:05
Fair enough!

**Comment by indigoxela** [comment] 2022-01-19 13:15
As this issue is mostly about the different i18nviews module, and there hasn't been activity for months, I'm closing this one (issue queue cleanup).

**Comment by indigoxela** [comment] 2022-02-16 09:48
Reopening this, as it now turned out where the problem is: we missed [this i18n issue and commit](https://www.drupal.org/project/i18n/issues/2632630), which got merged in 2017.

**Closed as completed** 2022-02-16 09:56 UTC
