### ISSUE TITLE
What needs work

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/i18n#1] opened 2016-03-27 04:06 UTC
Noticed a distinct need for language related help, so this is a start on i18n. It will not work as is, havent tested, so dont use in production. Its here so hopefully we can collaborate and fix it. Also havent informed the Drupal maintainer yet either.

So far only work done is to get it installing without error and to get the settings page for the main module and i18n strings working. Have not touched any of the other submodules at all.

Please if you try this, list whats broken in detail, here.
Checking off below what I've verified installs without error. This is **not** indicating that it actually works, just that it doesnt crash.

Working:
- [ ] <strike>Block languages</strike> (mostly in core and in Backdrop blocks are pretty different)
- [x] Contact translation
- [x] #11 Field translation
- [x] Internationalization
- [x] #2 Menu translation (very complex because of conflicts with core menu handling)
- [x] #8 Multilingual content
- [x] Multilingual forum (has been ported and moved to a [standalone project](https://github.com/backdrop-contrib/i18n_forum))
- [x] Multilingual select
- [x] Path translation
- [x] String translation
- [x] Synchronize translations
- [x] #3 Taxonomy translation
- [x] Translation redirect
- [x] Translation sets
- [ ] <strike>User mail translation</strike> (is in core)
- [ ] <strike>Variable translation</strike> (required module Variable won't get ported)

**Comment by bd0bd** [comment] 2016-03-31 21:46
@docwilmot, thank you for taking care of this important aspect of our CMS!

But please look at README.txt - this module is advertising BDSM - http://www.backdrop.net/  :smile:

**Comment by bd0bd** [comment] 2016-03-31 21:48
Now I have tried to install it and this is what I got:

![err](https://cloud.githubusercontent.com/assets/13515302/14191970/6c326f74-f7a3-11e5-9bb3-076b57416609.png)

**Comment by docwilmot** [comment] 2016-03-31 21:49
:smile: 

And why not?

Seriously, a search and replace error of course. This isn't half ported yet. Thanks anyway.

**Comment by bd0bd** [comment] 2016-03-31 21:55
And:

Fatal error: require_once(): Failed opening required '/home/p14352/www/domain.com/modules/i18n-1.x/i18n_string\i18n_string.inc' (include_path='.:/usr/local/php56/lib/php') in /home/p14352/www/domain.com/core/includes/bootstrap.inc on line 3629

**Comment by docwilmot** [comment] 2016-03-31 21:56
Did you try to install the Block submodule. Note in my checklist above only the checked submodules have been tested to install without error.

**Comment by bd0bd** [comment] 2016-03-31 21:57
I see. Ok.

**Comment by docwilmot** [comment] 2016-03-31 21:59
This will be a big thing to get done, its only a very very early start. If you could test out the ones that already checked, I would be grateful. And post here if there is any particular submodule you think should be a priority. I dont use this, never have, so I'm blind.

**Comment by bd0bd** [comment] 2016-03-31 22:00
I will test of cause.
But now I can not deinstall it.
I get this:

Fatal error: require_once(): Failed opening required '/home/p14352/www/domain.com/modules/i18n-1.x/i18n_string\i18n_string.inc' (include_path='.:/usr/local/php56/lib/php') in /home/p14352/www/domain.com/core/includes/bootstrap.inc on line 3629

**Comment by bd0bd** [comment] 2016-03-31 22:04
Menu tab disappeared

![men](https://cloud.githubusercontent.com/assets/13515302/14192338/aa058d7a-f7a5-11e5-86b9-22830a80bfc0.png)

**Comment by docwilmot** [comment] 2016-03-31 22:06
Oh no! You may need to do some work here sorry. Youll have to go into the submodule you installed (Block languages?)and comment out any lines saying `module_load_include(i18n_strings....)` and try and uninstall and hope for the best.

**Comment by bd0bd** [comment] 2016-03-31 22:08
It is not a problem for me - I will restore MySQL database as it was 24 hours ago :smile: 

**Update:** I have daily auto backup of all my databases and websites. So it is not a problem to restore to the previous stage any damaged database or website.

**Comment by bd0bd** [comment] 2016-03-31 22:20
I try to activate (from your list):

Internationalization
Menu translation
String translation
Translation sets

and have this error:

![err](https://cloud.githubusercontent.com/assets/13515302/14192740/47dc4fc8-f7a8-11e5-9faf-2d219dc16007.png)

**Comment by bd0bd** [comment] 2016-03-31 22:28
It seems the problem is with activating **Translation sets**.

**Comment by laryn** [comment] 2016-11-03 03:12
@docwilmot Might be worth adding [i18nviews](https://www.drupal.org/project/i18nviews) to the list above, even though it's a separate module in Drupal 7, since Views is in Backdrop core now?

**Comment by docwilmot** [comment] 2016-11-03 16:41
Hey @laryn thanks. I started this during an episode when quite a few people were discussing languages in Backdrop; I wasn't one of them and have no need for this module, but started it to get a solution going. I actually have little idea how languages work in Backdrop/Drupal so paradoxically I cant help much with this. So hopefully eventually someone who knows more about i18n and this module in general will take over and fix this.

**Comment by klonos** [comment] 2016-11-03 19:49
I am very interested in multilingual support, but unfortunately my php skills are very elementary and i18n is a very big/complex module.

**Comment by laryn** [comment] 2016-11-03 22:05
@klonos I'm no expert either but may try to pick away at a few of the key submodules. Would love to build this site I've got coming in Backdrop, but need to be able to translate menus and taxonomy. I'll start separate issues for each submodule as I get a chance to look at them.

@docwilmot Hope you don't mind I linked the new issue in your first post. Trying to keep things tied together.

**Comment by olafgrabienski** [comment] 2017-09-05 20:59
We talked recently in the Gitter channel and in the weekly [Dev meeting of Aug 31st,
 2017](https://www.youtube.com/watch?v=jz1GunNpTRw#t=15m35s) about *i18n*, beginning with the following Gitter post by myself:

> I'm considering to suggest to a customer to build a site with Backdrop instead of D8. There's one important requirement though: The site would be localized for German in the beginning (which will work), and at a certain point is has to become multilingual as well - not immediately (which won't work) but in about one year. Then the site owner needs definitely to translate content, taxonomy, views, menus, and a webform. My idea is to use a (modest) part of the website budget to sponsor work on the port of i18n and related modules. What would you say: is it realistic to get such a undertaking done?

There was a lot of feedback in Gitter, people expressed that they're interested in multilanguage sites as well, some said they will try to help, which is great! In the above mentioned Dev meeting we had the idea to put focus for one of the upcoming releases -- not 1.9 but probably 1.10 -- on the improvement of Backdrop's multilanguage capabilities. If I recall correct, the concept could include both the port of the most important *i18n* submodules and multilingual improvements in Backdrop core.

We talked also about different use cases to have a basis for a good concept and a reasonable prioritization of the development, one use case being a website of an international nonprofit organization which would be built or supported by the Backdrop4Good initiative.

Later in Gitter @serundeputy asked me to list the "top two priorities" of my use case in this queue. As I cited above, the site owner needs to translate content, taxonomy, views, menus, and a webform. Which are at least five important aspects for many sites (I leave webforms out here), and I actually forgot blocks, so we have six aspects. Difficult to pick two of them, I guess my customer (and a lot of other site multilingual site's owners) would need to translate at least content and taxonomy, and to handle views and blocks for different languages (where multilingual menus could be just several blocks, each with a menu in a different language). So, here are my top four for the moment: content, taxonomy, views, blocks.

**Comment by steve65140** [comment] 2017-09-14 07:44
Can I add a comment that I agree with @olafgrabienski --- you can't really build a site by selecting just two multilingual priorities picked out of the pile. To build even a basic multilingual site with D7 you need numerous modules enabled.

On my existing D7 sites clients require:
•	Content (field values, field labels & field help text) to be translatable.
•	Taxonomy terms to be translatable.
•	Views to show content in the visitors language.
•	Menus to be in the visitors language.
•	Blocks to be translatable and to show content in the visitors’ language.
•	Webforms to be translatable and to be shown in the visitors’ language.

Behind the scenes they have:
•	XML site maps in all the languages defined on the site (note that the D7 module XML site map doesn’t work with entity translation).
•	Alternate hreflang tags on the pages to help search engines.
•	A language selection tool that can be placed on the page by the site builder.

They also expect the backend admin pages to be in their language. I have D7 sites where English editors create content and French editors subsequently translate the content (and vice versa).

Once the above basic points are satisfied, the following make life easier for the content editors:
•	Display the language name/code in the content listing page (Backdrop core allows you to do this).
•	To have an overview of content translation status on the site e.g. which elements have no translation, which elements have an out of date translation and need updating. The Translation Overview module was good for this but it has been superseded by the Translation Management (TMGMT) module, which in my opinion is too complicated.

There is also the topic of handling multilingual site variables:
•	Site name.
•	Slogan.
•	Maintenance message.
•	Email texts.
•	Etc.

Backdrop got off to a good start with Content Translation working well, but that is only the tip of the iceberg of what is required to build and run multilingual sites.

So I would +1 to @olafgrabienski when he said that there are at least four things required (i.e. content, taxonomy, views, blocks) as a starting point.

**Comment by mazzech** [comment] 2017-10-31 13:41
I just create a D7 multilingual site, with a mixed use of Entity and Node translation. Entity translation is great for 90% of the stuff and most content types. But when it comes to landing pages, nothing beats Node translation IMHO: not only do I use Paragraphs a lot there (not multilingual in D7, and might never be). Even more important is the fact that landing page can be quite different in each language, which makes the 1:1 translation not the best option. D8 does not have node translation as far as I know... the D7 way in Backdrop (having both approaches) would be terrific.

**Comment by olafgrabienski** [comment] 2017-12-11 17:57
Fyi, I've started a discussion how to improve block translation in the Backdrop4Good issue queue: [Translate blocks](https://github.com/Backdrop4Good/backdrop4good.org/issues/39)

(We are working on the Backdrop4Good website as a use case for general multilanguage improvements in Backdrop.)

**Comment by indigoxela** [comment] 2020-03-05 09:27
I started working i18n_node. We're far from calling i18n ready yet and the module is big, so I'd like to ask for prioritization here:

- What should be fixed next?
- What should go (or has gone) to core?

**Comment by bd0bd** [comment] 2020-03-09 22:04
Well, I do not use Backdrop CMS any more and I am not going to use it in future.
Drupal 7 is better suitable for business.
Bye Backdrop!

**Comment by indigoxela** [comment] 2020-04-10 13:09
A lot of progress has been made. Testing is welcome.

I have two questions now:

1. Is i18n_select really obsolete? (I think so, but I actually never used it)
2. Should we move i18n_forum to its contrib module? (Forum isn't in core anymore)

**Comment by laryn** [comment] 2020-04-10 13:40
@indigoxela 

1. I've never used it either. [Here's a description](https://www.drupal.org/node/1279512).
2. Yes, sounds right.

And 3. Should **[i18n Views](https://www.drupal.org/project/i18nviews)** be wrapped (back) in since Views is in core now?

**Comment by indigoxela** [comment] 2020-04-10 13:47
> Should i18n Views be wrapped (back) in

Good question. I never used that either. What does it do? Are you using it?

**Comment by laryn** [comment] 2020-04-14 17:59
@indigoxela Yes, I use it on one or two D7 sites. It allows translation of Views labels, field rewrites, header/footer text areas, etc.

**Comment by mazzech** [comment] 2020-04-14 18:27
I used i18n Views several times, there are a few hickups, but the workarounds without the module are pretty dirty... ++ for having it migrated:-)

**Comment by indigoxela** [comment] 2020-04-15 06:08
Regarding i18n Views: I never needed it because views labels and header/footer text areas are translatable as-is, without any additional modules. At least in D7 - didn't need it yet in Backdrop. But if it works in D7, it should work in B core (or we should fix it there).

**Comment by indigoxela** [comment] 2020-05-10 09:12
It turned out that i18n_select still might be useful, so I ported it.

**Comment by herbdool** [comment] 2021-01-14 17:19
Can we close this? Seems like we've got everything covered in other issues.

**Closed as completed by herbdool** 2021-01-14 17:19 UTC
