### ISSUE TITLE
Translating terms is not prepopulating fields

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#74] opened 2021-04-23 16:10 UTC
When I translate a node, the fields get prepopulated with the source language info, which is helpful -- especially on fields that will end up remaining the same such as images. Those fields are starting out empty when translating terms.

**Comment by indigoxela** [comment] 2021-04-24 09:12
@laryn many thanks for reporting. I'll look into this a soon as more severe bugs are fixed.

Until then I may be able to figure out, what's missing for you, because when translating terms, the language fields are always prepopulated for me. :smile:

**Comment by indigoxela** [comment] 2022-01-19 13:13
Since I wasn't able to reproduce, and nobody else reported the same, I'm closing this issue as outdated (trying to cleanup the issues a bit). Feel free to reopen, if you figure out steps to reproduce.

**Closed as completed by indigoxela** 2022-01-19 13:13 UTC
