### ISSUE TITLE
i18n_menu issues

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#2] opened 2016-11-03 22:03 UTC
I'm going to [poke around](https://github.com/backdrop-contrib/i18n/compare/1.x...laryn:1.x) and see if I can get a few submodules running. I am testing i18n_menu and am running into this error when I try to configure a menu:

`Fatal error: Maximum execution time of 30 seconds exceeded in /path/to/backdrop/core/includes/errors.inc on line 271`

This is at **admin/structure/menu/manage/main-menu/configure**

Interestingly, **admin/structure/menu/manage/main-menu/translate** does not error out when visited. However, it does not function. Clicking on 'translate' reloads the page (with a language code appended to the URL, such as **admin/structure/menu/manage/main-menu/translate/de**) without proper breadcrumb or tabs.

<img width="948" alt="screen shot 2016-11-03 at 5 02 51 pm" src="https://cloud.githubusercontent.com/assets/871421/19987100/6fcdc6b2-a1e7-11e6-8cc0-aef622c176d3.png">

<img width="959" alt="screen shot 2016-11-03 at 5 03 09 pm" src="https://cloud.githubusercontent.com/assets/871421/19987104/73bf3daa-a1e7-11e6-9a41-e1dea75f5df8.png">

**Comment by laryn** [comment] 2017-07-13 05:28
Coming back to look at this one briefly... On a fresh install with i18n activated as well as i18n_menu, the above is accurate and I also see this in the watchdog log:

`Notice: Undefined property: stdClass::$language in i18n_langcode() (line 277 of /Users/user/buildkit/build/backdrop-demo/modules/i18n/i18n.module).`

https://github.com/backdrop-contrib/i18n/blob/1.x/i18n.module#L277

and then a TON of these: 

`Notice: Undefined property: stdClass::$option in form_select_options() (line 2842 of /Users/user/buildkit/build/backdrop-demo/core/includes/form.inc).`

**Comment by indigoxela** [comment] 2020-03-07 14:31
And again some years later... :wink: ... a [PR](https://github.com/indigoxela/i18n/pull/new/i18n-menu) as starting point.

This still needs work.

**Comment by indigoxela** [comment] 2020-03-08 13:50
Because of the fact that a _subset_ of [menu translation is in core](https://github.com/backdrop/backdrop-issues/issues/225), it's almost impossible to port i18n_menu.

UPDATE: the main problem is that I can't seem to get the i18n translation sets working properly.

**Comment by indigoxela** [comment] 2020-03-09 11:46
It seems, now I got translation sets working in i18n_menu.

The [PR](https://github.com/indigoxela/i18n/pull/new/i18n-menu) isn't ready yet, but testing is welcome. (Of course not on production sites.)

**Comment by indigoxela** [comment] 2020-03-16 08:58
How to test:

- Apply the patch
- Enable _only_ this submodule with its dependencies
- Go to admin/structure/menu/manage/YOUR-MENU/configure and play with the Multilingual options
- Choose "Translate and Localize" for one of the menus and translate some menu items with a language set (not language neutral)
- Switch between languages and verify that the right translations appear on pages
- Go to admin/structure/menu/manage/translation and inspect (and edit) the translation set
- Inspect dblog for any errors

And report any problems here.

**Comment by indigoxela** [comment] 2020-03-16 13:24
Applying the [patch](https://patch-diff.githubusercontent.com/raw/backdrop-contrib/i18n/pull/13.patch) is just one possible option.

Another option is to checkout the branch: https://github.com/indigoxela/i18n/tree/i18n-menu
(clone the indigoxela i18n repo and checkout the i18n-menu branch).

Be aware to _always disable (uninstall)_ the submodules not fixed in that branch.
To be on the safe side, you better uninstall all i18n modules and start fresh after cloning / switching branches.

**Comment by olafgrabienski** [comment] 2020-03-17 23:10
@indigoxela I've started to test `i18n`, see my first results below the Git related notes. Hope that helps as a starting point!

---

I've cloned your repo and checked out the branch - I hope successfully (I'm not *so* experienced with Git workflows). That's what I did in the `modules` directory:

- `git clone https://github.com/indigoxela/i18n.git`
- `cd i18n/`
- `git checkout i18n-menu`
  *Branch i18n-menu set up to track remote branch i18n-menu from origin.*
  *Switched to a new branch 'i18n-menu'*

---

**Messages after language import:**

I got three messages after importing the German language file on `admin/config/regional/translate/import`:

- Notice: Undefined index: group in i18n_string_locale_translate_import_form_submit() (line 281 of .../modules/i18n/i18n_string/i18n_string.module).
- Notice: Undefined index: group in i18n_string_locale_translate_import_form_submit() (line 282 of .../modules/i18n/i18n_string/i18n_string.module).
- Error: Class name must be a valid object or a string in i18n_string_textgroup() (line 369 of .../modules/i18n/i18n_string/i18n_string.module).

**Translating the menu**

- I've translated the *Primary navigation* menu, and the German translation (*Hauptnavigation*) appears in the list on the page `de/admin/structure/menu`. In contrast, so far it doesn't appear as title on `de/admin/structure/menu/manage/main-menu` and neither in the list of *Menus* in the *Admin bar*, even after translating the string also in the interface translation and clearing the cache.
- Regarding the translation in the list on the page `de/admin/structure/menu`: The translated menu description doesn't seem to allow HTML tags:
  - The English help text renders `<em>` tags as italics: The <em>Primary navigation</em> menu ...
  - The German translation displays the tag notation: Die `<em>Hauptnavigation</em>` ...

**Translating menu items**

- I was able to translate a menu item (*Home* => *Startseite*) but the translation doesn't appear where expected (frontend menu item, *Edit links* page filtered to German) and is not available on the *Translation sets* page (`admin/structure/menu/manage/translation/add`).

**Comment by indigoxela** [comment] 2020-03-18 09:37
Many thanks for testing this.

> I got three messages after importing the German language file on...

Good catch, I didn't test language import at all. The problem seems to occur in i18n_string submodule.

> I was able to translate a menu item (Home => Startseite) but the translation doesn't appear where expected...

Hm, that's really strange. So menu (item) translation doesn't work at all for you? And neither do translation sets?

**Comment by indigoxela** [comment] 2020-03-18 10:27
A quick thought: what happens when you refresh strings?

On admin/config/regional/translate/i18n_string check "Menu" and click "Refresh strings". Does this change anything?

**Comment by laryn** [comment] 2020-03-18 20:57
Here's how my test went.

 - I checked out the `i18n-menu` branch and enabled `i18n menu` (which made me activate dependencies).
 - I added a second language
 - I went to configure Primary Navigation (side note: the fieldset may look nicer as vertical tabs here):
![Screen Shot 2020-03-18 at 3 44 31 PM](https://user-images.githubusercontent.com/871421/77005852-8a20b480-692f-11ea-9092-31dee7edd19c.jpg)
 - I set it to "Translate and localize"
 - I changed one of the links on that menu to "English"
 - I could not find where to translate a link (I see "Edit" and "Delete" but no "Translate"):
![Screen Shot 2020-03-18 at 3 49 38 PM](https://user-images.githubusercontent.com/871421/77006254-22b73480-6930-11ea-8948-766a2df7f38d.jpg)
 - I went to the "Translate" tab and entered a translation for the menu itself.
 - Based on comments above I went to `admin/config/regional/translate/i18n_string`:
![Screen Shot 2020-03-18 at 3 53 53 PM](https://user-images.githubusercontent.com/871421/77006590-b4bf3d00-6930-11ea-8e67-00e51c66457e.jpg)
 - I selected the checkbox and clicked "Refresh Strings" ("Successfully refreshed 11 strings for Menu")
 - I went to `admin/structure/menu/manage/translation` but there were no Translation Sets. When I click "Add translation" I get this error:

> Too few arguments to function _i18n_menu_build_options(), 2 passed in /app/modules/i18n/i18n_menu/i18n_menu.admin.inc on line 197 and exactly 3 expected 

 - I see a bunch of these in the log (probably from the String Refresh step):

> Notice: Undefined offset: 7 in DatabaseLog->findCaller() (line 158 of /app/core/includes/database/log.inc).

> Notice: Undefined offset: 6 in DatabaseLog->findCaller() (line 154 of /app/core/includes/database/log.inc).

**Comment by olafgrabienski** [comment] 2020-03-19 12:36
> On admin/config/regional/translate/i18n_string check "Menu" and click "Refresh strings". Does this change anything?

Thanks for the hint! On first sight, it looks fine then. Message:

> Successfully refreshed 6 strings for Menu

When I went back to `admin/structure/menu/manage/main-menu`, I had to translate the item "Home" again. Did it, and same results as before: the translation doesn't appear.

PS: IIRC, you asked that in Zulip: Yes, I've enabled the option `Translate and Localize. Menu items with language will allow translations. Menu items without language will be localized.` in the *Multilingual Options* of the menu.

**Comment by indigoxela** [comment] 2020-03-19 12:43
> the translation doesn't appear.

And neither does the translation set on admin/config/regional/i18n_translation?

**Comment by olafgrabienski** [comment] 2020-03-19 12:45
> I could not find where to translate a link (I see "Edit" and "Delete" but no "Translate")

@laryn I also wondered how to translate a menu *item*. Currently, the `Translate` link isn't in the drop-button, instead you have to choose`Edit`, and on the Edit page you'll find a `Translate` tab.

**Comment by indigoxela** [comment] 2020-03-19 12:45
@laryn you seem to get a lot of php nagging (which I don't see). What php version are you using for that testing web?

**Comment by olafgrabienski** [comment] 2020-03-19 12:48
> And neither does the translation set on admin/config/regional/i18n_translation?

Yes, it does, but there is no item under "German", just an empty select list, so I can't select an item.

**Comment by indigoxela** [comment] 2020-03-19 13:05
> Yes, it does, but there is no item under "German", just an empty select list, so I can't select an item.

I think we're getting slightly closer. But I won't be able to dig into this before weekend. My conclusion so far: i18n_menu _might_ be useful as soon as i18n_translation (translation sets) work reliably.

@laryn BTW, it's ambitious to already make suggestions for better UX, when it's not yet clear if we  manage to get the modules running anyway. :smiley: We're still far from that.

**Comment by laryn** [comment] 2020-03-20 17:16
> @laryn BTW, it's ambitious to already make suggestions for better UX

I guess I'm an over-achiever!

As far as PHP, I am testing in a Lando environment with PHP 7.3.14.

**Comment by indigoxela** [comment] 2020-03-20 17:30
> I guess I'm an over-achiever!

:rofl:

No, seriously, if we ever manage to get i18n running, we should of course improve the UX.

**Next step in testing:** another [PR](https://github.com/backdrop-contrib/i18n/pull/18)

It might contain a breaking change - I'm not really sure yet.
People who have cloned my repo have to pull and then switch to the new branch **i18n-menu-part2**

Flush caches and then try to translate a menu item via admin/structure/menu/item/[item num]/translate

@laryn Regarding the php errors you see - I'm a bit clueless as I can't reproduce them.

**Comment by indigoxela** [comment] 2020-03-25 14:16
My PR has been merged, testing is welcome.

**Comment by indigoxela** [comment] 2020-04-30 11:40
For people interested in testing: if you do so start fresh (code from 1.x, fresh config, fresh db), as there were many changes.

**Comment by indigoxela** [comment] 2020-12-06 11:36
I'm pretty sure, this issue is completely outdated.
Feel free to re-open if that's not the case. But very likely it would be better to open a new one. Many thanks for your contributions.

**Closed as completed by indigoxela** 2020-12-06 11:36 UTC
